#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "content", "blog");
const OUTPUT_FILE = path.join(ROOT, "lib", "blog-data.generated.ts");
const LANGS = ["en", "fr", "nl"];

function escapeTemplate(s) {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

const slugs = fs
  .readdirSync(CONTENT_DIR)
  .filter((d) => fs.statSync(path.join(CONTENT_DIR, d)).isDirectory());

const posts = slugs.map((slug) => {
  const perLang = {};
  for (const lang of LANGS) {
    const file = path.join(CONTENT_DIR, slug, `${lang}.md`);
    if (!fs.existsSync(file)) {
      throw new Error(`Missing translation: ${file}`);
    }
    const raw = fs.readFileSync(file, "utf8");
    const parsed = matter(raw);
    perLang[lang] = { ...parsed.data, content: parsed.content.trim() };
  }
  const base = perLang.en;
  return {
    slug,
    icon: base.icon,
    date: base.date,
    authors: base.authors,
    title: Object.fromEntries(LANGS.map((l) => [l, perLang[l].title])),
    description: Object.fromEntries(LANGS.map((l) => [l, perLang[l].description])),
    category: Object.fromEntries(LANGS.map((l) => [l, perLang[l].category])),
    tags: Object.fromEntries(LANGS.map((l) => [l, perLang[l].tags])),
    readTime: Object.fromEntries(LANGS.map((l) => [l, perLang[l].readTime])),
    content: Object.fromEntries(LANGS.map((l) => [l, perLang[l].content])),
  };
});

posts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

const icons = [...new Set(posts.map((p) => p.icon))].sort();

let out = `// AUTO-GENERATED by scripts/build-blog.mjs — do not edit.\n`;
out += `// Source: content/blog/<slug>/<lang>.md\n`;
out += `import type { LucideIcon } from "lucide-react";\n`;
out += `import { ${icons.join(", ")} } from "lucide-react";\n`;
out += `import type { SupportedLanguages } from "@/lib/translations";\n\n`;

out += `type Localized = Record<SupportedLanguages, string>;\n\n`;

out += `export interface BlogPostData {\n`;
out += `  slug: string;\n`;
out += `  icon: LucideIcon;\n`;
out += `  date: string;\n`;
out += `  authors: { name: string; linkedin: string }[];\n`;
out += `  title: Localized;\n`;
out += `  description: Localized;\n`;
out += `  category: Localized;\n`;
out += `  tags: Record<SupportedLanguages, string[]>;\n`;
out += `  readTime: Localized;\n`;
out += `  content: Localized;\n`;
out += `}\n\n`;

out += `export const blogPosts: BlogPostData[] = [\n`;
for (const p of posts) {
  out += `  {\n`;
  out += `    slug: ${JSON.stringify(p.slug)},\n`;
  out += `    icon: ${p.icon},\n`;
  out += `    date: ${JSON.stringify(p.date)},\n`;
  out += `    authors: ${JSON.stringify(p.authors)},\n`;
  for (const field of ["title", "description", "category", "readTime"]) {
    out += `    ${field}: {\n`;
    for (const lang of LANGS) {
      out += `      ${lang}: ${JSON.stringify(p[field][lang])},\n`;
    }
    out += `    },\n`;
  }
  out += `    tags: {\n`;
  for (const lang of LANGS) {
    out += `      ${lang}: ${JSON.stringify(p.tags[lang])},\n`;
  }
  out += `    },\n`;
  out += `    content: {\n`;
  for (const lang of LANGS) {
    out += `      ${lang}: \`\n${escapeTemplate(p.content[lang])}\n\`.trim(),\n`;
  }
  out += `    },\n`;
  out += `  },\n`;
}
out += `];\n`;

fs.writeFileSync(OUTPUT_FILE, out);
console.log(`Generated ${posts.length} posts → ${path.relative(ROOT, OUTPUT_FILE)}`);
